name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  browserstack-username:
    description: 'Browserstack screenshot api username'
  action:
    description: 'Execute sub action. Available actions [generate-screenshots]'
    required: true
    default: 'generate-screenshots'
  website-domain:
    description: 'Website base url'
  screenshot-page-urls:
    description: "Website page urls"

outputs:
  urls:
    description: 'Output urls of url collectors'
  job-result:
    description: 'Result of the finished jobs'
  screenshots-directory:
    description: 'Screenshots download directory'
runs:
  using: 'node12'
  main: 'index.js'
