name: 'Browserstack Screenshots CI/CD'
description: 'Greet someone and record the time'
inputs:
  browserstack-username:
    description: 'Browserstack screenshot api username'
  action:
    description: 'Execute sub action. Available actions [generate-screenshots]'
    required: true
    default: 'generate-screenshots'
  website-domain:
    description: 'Website base url'
  screenshot-page-urls:
    description: "Website page urls"
  gatsby-public-folder:
    description: "Path to gatsby's public folder"
  job-result:
    description: "Screenshots result json"
  result-path:
    description: "Output path"
  json-payload:
    description: "Slack json payload"

outputs:
  urls:
    description: 'Output urls of url collectors'
  job-result:
    description: 'Result of the finished jobs'
  screenshots-directory:
    description: 'Screenshots download directory'
  github-run-id:
    description: 'Id of github run'
runs:
  using: 'node12'
  main: 'index.js'
