name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  browserstack-username:
    description: 'Browserstack screenshot api username'
    required: true
  action:
    description: 'Execute sub action. Available actions [generate-screenshots]'
    required: true
    default: 'generate-screenshots'
outputs:
  job-result: # id of output
    description: 'Result of the finished jobs'
runs:
  using: 'node12'
  main: 'index.js'
