name: "Screenshots"

on: [push]

jobs:

  generate-screenshots-job:
    runs-on: ubuntu-latest
    name: Make screenshots
    steps:

    # Load repository onto ubuntu worker machine
    - name: Checkout
      uses: actions/checkout@v2

    # Collect static gatsby site urls
    - name: Gatsby collect urls
      id: collect-static-gatsby
      uses: frank7huysen/browserstack-screenshots@v1.4.6
      with:
        action: 'collect-static-gatsby'
        gatsby-public-folder: ./gatsby-public
        website-domain: https://staging.try.theaterthuis.nl/nl-nl/

    # Generate screenshots
    - name: Generate screenshots
      id: generate-screenshots
      env:
        CI: true
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_PASSWORD: ${{ secrets.BROWSERSTACK_PASSWORD }}
      uses: frank7huysen/browserstack-screenshots@v1.4.6
      with:
        action: 'generate-screenshots'
        screenshot-page-urls: ${{ steps.collect-static-gatsby.outputs.urls }}

    # Download screenshots from browserstack
    - name: Download screenshots
      id: download-screenshots
      uses: frank7huysen/browserstack-screenshots@v1.4.6
      with:
        action: 'download-screenshots'
        job-result: ${{ steps.generate-screenshots.outputs.job-result }}

    # Generate pdf with screenshots
    - name: Generate result PDF
      id: generate-pdf
      uses: frank7huysen/browserstack-screenshots@v1.4.6
      with:
        action: 'generate-pdf'

    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: browserstack-screenshots
        path: ${{ steps.download-screenshots.outputs.screenshots-directory }}



