name: "Screenshots"

on: [push]

jobs:
  generate-screenshots-job:
    runs-on: ubuntu-latest
    name: Make screenshots
    steps:

    # Generate screenshots
    - name: Generate screenshots
      id: generate-screenshots
      env:
        CI: true
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_PASSWORD: ${{ secrets.BROWSERSTACK_PASSWORD }}
      uses: frank7huysen/browserstack-screenshots@v1.3.22
      with:
        action: 'generate-screenshots'

    # Use the output from the `hello` step
    - name: Show job result
      run: echo "The result of the job was ${{ steps.generate-screenshots.outputs.job-result }}"

    # Download screenshots from browserstack
    - name: Download screenshots
      id: download-screenshots
      uses: frank7huysen/browserstack-screenshots@v1.3.22
      with:
        action: 'download-screenshots'
        job-result: ${{ steps.generate-screenshots.outputs.job-result }}

    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: Upload screenshot as artifact
        path: /screenshots


