name: "Screenshots"

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Make screenshots
    steps:
    - name: Hello world action step
      id: hello
      uses: frank7huysen/browserstack-screenshots@v1.3.1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"